#!/bin/bash

ME=${0##*/}
function usage()
{
  echo "
    $ME: prepare to run ipic3d job for supplied parameters
  
    usage: $ME -d datadir <XLEN> <YLEN>
    
      <XLEN>: number of processors in X direction
      <YLEN>: number of processors in Y direction
  "
}

if [ $# -lt 2 ]; then usage; exit 1; fi

  . $IPIC_HOME/scripts/ipicrun15x15meshinp

  PPN=8
  NUM_PROCS=$(($XLEN*$YLEN))
  NUM_NODES=$((($NUM_PROCS-1)/$PPN+1))

  : create job script from template
  sed " \
    s@nodes=[0-9][0-9]*@nodes=$NUM_NODES@ ;
    s@ppn=[0-9][0-9]*@ppn=$PPN@ ;
    s@XLEN=.*@XLEN=$XLEN@
    s@YLEN=.*@YLEN=$YLEN@
    s@NUM_PROCS=.*@NUM_PROCS=$NUM_PROCS@
    s@DATA=.*@DATA=$DATA@
  " job.sh > "$DATA"/job.sh
echo "
Use:

   vim $DATA/job.sh $DATA/parameters.inp

 to check that job script and input files are correct and then do:

   sbatch $DATA/job.sh
"
