#!/bin/bash

ME=${0##*/}
function usage()
{
  echo "
    $ME: get striping parameters for file or directory
  
    usage: $ME <dir>
  "
}

if [ ${1:-a} == "--help" ] || [ ${1:-a} == "-h" ]; then usage; exit 1; fi

set -x
lfs getstripe "$@"
